apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-amazon-geodata
  labels:
    app: {{ .Release.Name }}-amazon-geodata
    {{- include "chirpstack.labels" . | nindent 4 }}
data:
  amazon_conservation_areas.geojson: |-
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            "name": "Jaú National Park",
            "type": "national_park",
            "status": "UNESCO_heritage",
            "country": "Brazil",
            "established": "1980",
            "centerLat": -1.9500,
            "centerLng": -61.7500
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-62.1, -1.6],
              [-61.3, -1.6],
              [-61.3, -2.3],
              [-62.1, -2.3],
              [-62.1, -1.6]
            ]]
          }
        },
        {
          "type": "Feature",
          "properties": {
            "name": "Anavilhanas National Park",
            "type": "national_park",
            "status": "protected",
            "country": "Brazil",
            "established": "1981",
            "centerLat": -2.6389,
            "centerLng": -60.7500
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-61.0, -2.3],
              [-60.5, -2.3],
              [-60.5, -3.0],
              [-61.0, -3.0],
              [-61.0, -2.3]
            ]]
          }
        },
        {
          "type": "Feature",
          "properties": {
            "name": "Mamirauá Reserve",
            "type": "sustainable_use_reserve",
            "status": "sustainable_use",
            "country": "Brazil",
            "established": "1996",
            "centerLat": -2.3083,
            "centerLng": -65.8639
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-66.2, -2.0],
              [-65.5, -2.0],
              [-65.5, -2.6],
              [-66.2, -2.6],
              [-66.2, -2.0]
            ]]
          }
        }
      ]
    }

  amazon_indigenous_territories.geojson: |-
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            "name": "Yanomami Territory",
            "group_name": "Yanomami",
            "status": "demarcated",
            "country": "Brazil",
            "population": 26780,
            "centerLat": 2.4467,
            "centerLng": -63.3425
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-64.0, 2.0],
              [-62.6, 2.0],
              [-62.6, 3.0],
              [-64.0, 3.0],
              [-64.0, 2.0]
            ]]
          }
        },
        {
          "type": "Feature",
          "properties": {
            "name": "Vale do Javari",
            "group_name": "Multiple Indigenous Groups",
            "status": "demarcated",
            "country": "Brazil",
            "population": 6000,
            "centerLat": -5.5000,
            "centerLng": -72.0000
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-72.5, -5.0],
              [-71.5, -5.0],
              [-71.5, -6.0],
              [-72.5, -6.0],
              [-72.5, -5.0]
            ]]
          }
        }
      ]
    }

  amazon_river_networks.geojson: |-
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            "name": "Rio Negro",
            "type": "blackwater_river",
            "basin": "Amazon",
            "country": "Brazil",
            "flow_rate": 28.400
          },
          "geometry": {
            "type": "LineString",
            "coordinates": [
              [-60.0, -3.0],
              [-60.5, -2.8],
              [-61.0, -2.7],
              [-61.5, -2.5],
              [-62.0, -2.3]
            ]
          }
        },
        {
          "type": "Feature",
          "properties": {
            "name": "Rio Solimões",
            "type": "whitewater_river",
            "basin": "Amazon",
            "country": "Brazil",
            "flow_rate": 101.000
          },
          "geometry": {
            "type": "LineString",
            "coordinates": [
              [-67.0, -3.3],
              [-66.0, -3.4],
              [-65.0, -3.5],
              [-64.0, -3.6],
              [-63.0, -3.5]
            ]
          }
        }
      ]
    }

  amazon_deforestation_risk.geojson: |-
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            "id": 1,
            "risk_level": "high",
            "cause": "agricultural_expansion",
            "year_observed": 2023,
            "forest_type": "terra_firme",
            "centerLat": -3.8500,
            "centerLng": -55.2000
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-55.5, -3.6],
              [-54.9, -3.6],
              [-54.9, -4.1],
              [-55.5, -4.1],
              [-55.5, -3.6]
            ]]
          }
        },
        {
          "type": "Feature",
          "properties": {
            "id": 2,
            "risk_level": "medium",
            "cause": "illegal_logging",
            "year_observed": 2023,
            "forest_type": "varzea_floodplain",
            "centerLat": -4.1000,
            "centerLng": -59.5000
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-59.8, -3.9],
              [-59.2, -3.9],
              [-59.2, -4.3],
              [-59.8, -4.3],
              [-59.8, -3.9]
            ]]
          }
        },
        {
          "type": "Feature",
          "properties": {
            "id": 3,
            "risk_level": "critical",
            "cause": "road_construction",
            "year_observed": 2024,
            "forest_type": "terra_firme",
            "centerLat": -7.3000,
            "centerLng": -72.5000
          },
          "geometry": {
            "type": "Polygon",
            "coordinates": [[
              [-72.8, -7.1],
              [-72.2, -7.1],
              [-72.2, -7.5],
              [-72.8, -7.5],
              [-72.8, -7.1]
            ]]
          }
        }
      ]
    }