apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescaledb
  labels:
    app: {{ .Release.Name }}-timescaledb
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: NodePort  # Change to NodePort for better accessibility
  ports:
  - port: {{ .Values.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
    nodePort: {{ .Values.service.nodePort | default 32432 }}  # Expose on a specific nodePort
  selector:
    app: {{ .Release.Name }}-timescaledb