apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-connectivity-fairy
  labels:
    app: {{ .Release.Name }}-connectivity-fairy
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-connectivity-fairy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-connectivity-fairy
        {{- include "chirpstack.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}-connectivity-fairy
      {{- end }}
      containers:
      - name: connectivity-fairy
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: connectivity-fairy-config
          mountPath: /usr/share/nginx/html
        - name: connectivity-script
          mountPath: /scripts
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      # Sidecar container for connectivity checking
      - name: connectivity-checker
        image: "bitnami/kubectl:latest"
        command: ["/bin/bash", "-c", "/scripts/connectivity-check.sh"]
        volumeMounts:
        - name: connectivity-script
          mountPath: /scripts
        - name: connectivity-data
          mountPath: /data
        env:
        - name: SCAN_INTERVAL
          value: "{{ .Values.config.scanInterval }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: connectivity-fairy-config
        configMap:
          name: {{ .Release.Name }}-connectivity-fairy-ui
      - name: connectivity-script
        configMap:
          name: {{ .Release.Name }}-connectivity-fairy-scripts
          defaultMode: 0755
      - name: connectivity-data
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}