{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-connectivity-fairy
  labels:
    app: {{ .Release.Name }}-connectivity-fairy
    {{- include "chirpstack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-connectivity-fairy
  labels:
    app: {{ .Release.Name }}-connectivity-fairy
    {{- include "chirpstack.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-connectivity-fairy
  labels:
    app: {{ .Release.Name }}-connectivity-fairy
    {{- include "chirpstack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-connectivity-fairy
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-connectivity-fairy
  namespace: {{ .Release.Namespace }}
{{- end }}