apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-config
  labels:
    app: {{ .Release.Name }}-kafka
    {{- include "chirpstack.labels" . | nindent 4 }}
data:
  KAFKA_KRAFT_CLUSTER_ID: "{{ .Values.config.kraftClusterId }}"