apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-init-config
  labels:
    app: {{ .Release.Name }}-kafka
    {{- include "chirpstack.labels" . | nindent 4 }}
data:
  generate-config.sh: |
    #!/bin/sh
    set -e
    
    # Extract the pod index as an integer from the hostname
    # This is critical for KRaft as it requires NODE_ID to be an integer
    KAFKA_ID=$(echo $POD_NAME | awk -F'-' '{print $NF}')
    
    # Get the FQDN for advertised listeners
    HOSTNAME="${POD_NAME}.${POD_NAME%-*}.${KUBE_NAMESPACE}.svc.cluster.local"
    
    # Create the environment file with the node ID as an integer and advertised listeners
    cat > /mnt/config/kafka-env.sh << EOF
    export KAFKA_CFG_NODE_ID=$KAFKA_ID
    export KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${HOSTNAME}:9092,EXTERNAL://${HOSTNAME}:9094
    EOF
    
    # Make it executable
    chmod +x /mnt/config/kafka-env.sh
    echo "Generated Kafka environment with NODE_ID=${KAFKA_ID} and ADVERTISED_LISTENERS for ${HOSTNAME}"