apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emqx-headless
  labels:
    app: {{ .Release.Name }}-emqx
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: {{ .Values.service.mqttsPort }}
      targetPort: mqtts
      protocol: TCP
      name: mqtts
    - port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
  selector:
    app: {{ .Release.Name }}-emqx