# Geo-Enrichment Service Configuration

replicaCount: 1

image:
  repository: node
  tag: 16-alpine
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Configuration for database connection
database:
  enabled: true
  host: "{{ .Release.Name }}-timescaledb"
  port: 5432
  name: "iot_timeseries"
  user: "postgres"
  password: "postgres"

# Location Data Configuration
locationData:
  # Update interval for refreshing location data (in minutes)
  refreshInterval: 30
  # Whether to import default locations on startup
  importDefaultLocations: true
  # Default locations (can be overridden with ConfigMap)
  defaultLocations: []