apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-init
  labels:
    app: {{ .Release.Name }}-postgresql
data:
  init-chirpstack-dbs.sh: |
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE DATABASE chirpstack_ns;
      CREATE DATABASE chirpstack_as;
      
      \c chirpstack_ns
      CREATE EXTENSION pg_trgm;
      CREATE EXTENSION hstore;
      
      \c chirpstack_as
      CREATE EXTENSION pg_trgm;
      CREATE EXTENSION hstore;
    EOSQL
