apiVersion: v1
kind: Secret
metadata:
  name: chirpstack-db-credentials
  labels:
    app: {{ .Release.Name }}-postgresql
type: Opaque
data:
  password: {{ .Values.global.postgresql.password | default "chirpstack" | b64enc | quote }}
