# Default values for chirpstack-gateway-bridge
replicaCount: 1

image:
  repository: chirpstack/chirpstack-gateway-bridge
  tag: 3.14.3
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

service:
  type: NodePort
  port: 1700
  protocol: UDP
  nodePort: 31700

config:
  logging:
    level: "info"
  backend:
    type: "semtech_udp"
    semtech_udp:
      udp_bind: "0.0.0.0:1700"
  integration:
    mqtt:
      server: "tcp://emqx:1883"
      event_topic_template: "gateway/{{ .GatewayID }}/event/{{ .EventType }}"
      command_topic_template: "gateway/{{ .GatewayID }}/command/#"
