apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chirpstack-network-server
  labels:
    app: {{ .Release.Name }}-chirpstack-network-server
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-chirpstack-network-server
