apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chirpstack-gateway-bridge
  labels:
    app: {{ .Release.Name }}-chirpstack-gateway-bridge
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-chirpstack-gateway-bridge
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-chirpstack-gateway-bridge
    spec:
      containers:
        - name: chirpstack-gateway-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: udp
              containerPort: 1700
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
              subPath: chirpstack-gateway-bridge.toml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-chirpstack-gateway-bridge-config
