apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chirpstack-gateway-bridge
  labels:
    app: {{ .Release.Name }}-chirpstack-gateway-bridge
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: {{ .Values.service.protocol }}
      name: udp
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-chirpstack-gateway-bridge
