apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sensor-map
  labels:
    app: {{ .Release.Name }}-sensor-map
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  - port: 3000
    targetPort: api
    protocol: TCP
    name: api
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ add .Values.service.nodePort 1 }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-sensor-map